### ISSUE TITLE
[2.0.0] Release

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCampOS#262]
# Version 2.0.0

Currently, the docs have the mostly expected outline of the [test-utils](). However, the actual test utils do not conform to this.

## TODOs

- [x] Remove unneeded utility functions (all undocumented ones)
- [x] `controlWrapper` function
  - Refactor to require callback to throw on non-success
- [x] `get<LOG_FILE>` functions
  - Refactor to not throw on empty files - I cannot remember if there was a good reason for this, but I can no longer think of one
- [ ] Do **NOT** remember which bottom panel tab (hints, console, tests) was selected between lessons

**Comment by ShaunSHamilton** [comment]
@moT01 I am trying to decide whether to implement this feature or not:
> Do NOT remember which bottom panel tab (hints, console, tests) was selected between lessons

Basically, the current behaviour is to remain on the `console` tab in the next lesson, if it was previously clicked on. However, I am not sure this is desirable?

**Comment by moT01** [comment]
I think I would prefer it to go back to the hints on a new lesson, but it does feel like just a preference - some may prefer it stay on the console. What do you like?

**Comment by ShaunSHamilton** [comment]
I think going back to the tests makes sense, because the console is meant for more of a debugging/more info workflow - the step after reading the test text.
